import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "react-responsive-pagination/themes/classic.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className + " text-gray-900 dark:text-gray-100"}>
        {children}
      </body>
    </html>
  );
}
